### ISSUE TITLE
How to retrieve Display Name?

### ISSUE THREAD

**Issue by Twinsen343** [spinegar/sugarcrm7-api-wrapper-class#29]
Hey Man,

Amazing Work!! - I have a quick question; how can I pull out the display name for an item and not the system name?

Some fields I want to pull out have an initial as the system name but the full name as the display name and that is what I want to pull out.

Any help would be appreciated!

Cheers

**Comment by ithakaben** [comment]
I happened to see this 8 months after you posted it, but in case it is helpful, you can do this with the module/Enum endpoint. This will return an array of the system names => display names
` $array = $sugar->getEndpoint('<module name>/enum/<field name>');`

**Comment by Twinsen343** [comment]
@ithakaben hey man, I found out by including the language file I could use the array name / System Value to retrieve the display name of the value  from the array
