### ISSUE TITLE
Would this work with earlier versions

### ISSUE THREAD

**Issue by skynet** [spinegar/sugarcrm7-api-wrapper-class#30]
Would this work with earlier versions, for example v4_1 for SugarCRM 6.7.x	
where REST is at: `http://{site url}/service/v4_1/rest.php`

**Comment by spinegar** [comment]
This would not. I recommend https://github.com/asakusuma/SugarCRM-REST-API-Wrapper-Class

**Comment by skynet** [comment]
:+1:
